version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:45"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
